import type { ThemeTokens } from "./types";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  base: "light" | "dark";
  tokens: ThemeTokens;
}

export const DEFAULT_THEME_ID = "serene-blue";

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "serene-blue",
    name: "Serene Blue",
    description: "Soothing blues with crisp highlights for focused planning.",
    base: "light",
    tokens: {
      background: "#f4f6ff",
      surface: "#eef2ff",
      surfaceAlt: "#dbeafe",
      card: "#ffffff",
      border: "#cbd5ff",
      textPrimary: "#1f2937",
      textSecondary: "#4b5563",
      header: "#e0e7ff",
      accent: "#7c3aed",
      accentContrast: "#ffffff",
      button: "#4f46e5",
      buttonText: "#ffffff",
      progress: "#6366f1",
      placeholder: "#7c83f8",
    },
  },
  {
    id: "forest-mist",
    name: "Forest Mist",
    description: "Muted greens with warm neutrals for a restorative workspace.",
    base: "light",
    tokens: {
      background: "#f3f7f4",
      surface: "#ecf4ed",
      surfaceAlt: "#d9eadf",
      card: "#ffffff",
      border: "#c6d8ca",
      textPrimary: "#1f2a24",
      textSecondary: "#4b5d50",
      header: "#d9eadf",
      accent: "#2f855a",
      accentContrast: "#ffffff",
      button: "#2f855a",
      buttonText: "#f0fff4",
      progress: "#48bb78",
      placeholder: "#5c9275",
    },
  },
  {
    id: "sunset-haze",
    name: "Sunset Haze",
    description: "Warm ambers and rose accents for creative sessions.",
    base: "light",
    tokens: {
      background: "#fff7f2",
      surface: "#fff0e5",
      surfaceAlt: "#ffe4d6",
      card: "#ffffff",
      border: "#ffd6ba",
      textPrimary: "#3b2f2a",
      textSecondary: "#5f4239",
      header: "#ffe4d6",
      accent: "#f97316",
      accentContrast: "#ffffff",
      button: "#ea580c",
      buttonText: "#fff7ed",
      progress: "#fb923c",
      placeholder: "#d86b3b",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep slate tones with electric accents for night owls.",
    base: "dark",
    tokens: {
      background: "#0f172a",
      surface: "#111c30",
      surfaceAlt: "#14213d",
      card: "#1f2937",
      border: "#28355a",
      textPrimary: "#f8fafc",
      textSecondary: "#cbd5f5",
      header: "#14213d",
      accent: "#38bdf8",
      accentContrast: "#04121f",
      button: "#2563eb",
      buttonText: "#eff6ff",
      progress: "#38bdf8",
      placeholder: "#94a3b8",
    },
  },
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    description: "Soft pinks and mauves for gentle project flow.",
    base: "light",
    tokens: {
      background: "#fdf4f8",
      surface: "#fbe9f2",
      surfaceAlt: "#f7d9e9",
      card: "#ffffff",
      border: "#f3c4dd",
      textPrimary: "#37223b",
      textSecondary: "#5b3a5f",
      header: "#f7d9e9",
      accent: "#d946ef",
      accentContrast: "#330033",
      button: "#c026d3",
      buttonText: "#fdf4ff",
      progress: "#e879f9",
      placeholder: "#d14bbd",
    },
  },
  {
    id: "slate-minimal",
    name: "Slate Minimal",
    description: "Neutral slate palette for analytical clarity.",
    base: "light",
    tokens: {
      background: "#f5f6f8",
      surface: "#f0f1f4",
      surfaceAlt: "#e2e5eb",
      card: "#ffffff",
      border: "#d1d4db",
      textPrimary: "#1f2933",
      textSecondary: "#4a5565",
      header: "#e2e5eb",
      accent: "#2563eb",
      accentContrast: "#ffffff",
      button: "#1d4ed8",
      buttonText: "#f8fafc",
      progress: "#3b82f6",
      placeholder: "#5b6573",
    },
  },
];

